
import json

new_facilities = [
  {
    'slug': 'sevatirtham-nursing-home-baruipur',
    'nameBn': 'সেবাতীর্থম নার্সিং হোম ও ডায়াগনস্টিক',
    'nameEn': 'Sevatirtham Nursing Home & Diagnostic',
    'type': 'nursing_home',
    'typeBn': 'নার্সিং হোম ও ডায়াগনস্টিক সেন্টার',
    'taglineBn': 'বারুইপুর রেল স্টেশনের সন্নিকটে সুলভ মূল্যে আধুনিক চিকিৎসা, সার্জারি ও ২৪ ঘণ্টার জরুরি পরিষেবা',
    'overviewBn': 'সেবাতীর্থম নার্সিং হোম বারুইপুর রেলওয়ে স্টেশনের কাছে শাহজাহান রোডে অবস্থিত একটি বিশ্বস্ত চিকিৎসাকেন্দ্র। ২০০৪ সালে প্রয়াত ডাঃ সুধীর চন্দ্র দত্তের পরিকল্পনায় এটি প্রতিষ্ঠিত হয় এবং বর্তমানে ডাঃ বনানী দত্তের তত্ত্বাবধানে পরিচালিত হচ্ছে। এখানে সুলভ খরচে সাধারণ ও ল্যাপারোস্কোপিক সার্জারি, স্ত্রীরোগ ও প্রসূতি সেবা, শিশু বিভাগ, আধুনিক প্যাথলজি ও ডিজিটাল ডায়াগনস্টিক সুবিধা রয়েছে। নার্সিং হোমটি পশ্চিমবঙ্গ সরকারের স্বাস্থ্যসাথী প্রকল্পের আওতাভুক্ত এবং স্টার হেলথ সহ বিভিন্ন মেডিক্লেইম ক্যাশলেস বীমা সুবিধা প্রদান করে।',
    'addressBn': 'শাহজাহান রোড, বারুইপুর (রেলওয়ে স্টেশন সংলগ্ন), দক্ষিণ ২৪ পরগনা, কলকাতা - ৭০০১৪৪',
    'addressEn': 'Sajahan Road, Near Baruipur Railway Station, Baruipur, South 24 Parganas, Kolkata - 700144',
    'landmarkBn': 'বারুইপুর রেলওয়ে স্টেশন সংলগ্ন, শাহজাহান রোড',
    'phone': '9831324595',
    'altPhone': '9088377220',
    'emergencyPhone': '033-2433-8156',
    'whatsapp': '+916291123465',
    'email': 'sevatirthamnursinghome@gmail.com',
    'website': 'https://www.sevatirthamnursinghome.com',
    'googleMapUrl': 'https://maps.google.com/?q=Sevatirtham+Nursing+Home+Baruipur',
    'openingHoursBn': 'জরুরি বিভাগ ও ইনডোর: ২৪ ঘণ্টা খোলা | বহির্বিভাগ (OPD): সকাল ১০:০০ - রাত ৯:০০',
    'isOpen24Hours': True,
    'hasEmergency': True,
    'hasPharmacy': True,
    'hasDiagnostic': True,
    'hasAmbulance': True,
    'swasthyaSathiAccepted': True,
    'insuranceAccepted': True,
    'establishedYear': '২০০৪',
    'bedCapacity': '২৫ শয্যা',
    'coverImage': '/images/health/sevatirtham-nursing-home.jpg',
    'images': [
      '/images/health/sevatirtham-nursing-home.jpg',
      '/images/health/sevatirtham-nursing-home-slide1.jpg'
    ],
    'keyServicesBn': [
      '২৪ ঘণ্টা জরুরি পরিষেবা ও ইনডোর ভর্তি',
      'জেনারেল সার্জারি ও অ্যাডভান্সড ল্যাপারোস্কোপিক অপারেশন',
      'নরমাল ও সিজারিয়ান ডেলিভারি এবং মাতৃত্বকালীন পরিচর্যা',
      'স্বাস্থ্যসাথী কার্ডে বিনামূল্যে চিকিৎসার সরকারি সুবিধা',
      'স্টার হেলথ ও টিপিএ মেডিক্লেইম ক্যাশলেস হসপিটালাইজেশন',
      'নবজাতক ও শিশু বিশেষজ্ঞ পরামর্শ ও চিকিৎসা'
    ],
    'diagnosticFacilitiesBn': [
      'ডিজিটাল এক্স-রে (Digital X-Ray)',
      'আল্ট্রাসনোগ্রাফি (USG)',
      'ইসিজি (ECG)',
      'সম্পূর্ণ অটোমেটেড প্যাথলজি ও বায়োকেমিস্ট্রি ল্যাব টেস্ট'
    ],
    'doctorsCount': 5,
    'doctors': [
      {
        'id': 'sevatirtham-doc-1',
        'nameBn': 'ডাঃ বনানী দত্ত',
        'nameEn': 'Dr. Banani Dutta',
        'degrees': 'MBBS, General Physician',
        'specialtyKey': 'general_physician',
        'specialtyBn': 'জেনারেল ফিজিশিয়ান ও আরএমও (প্রোপ্রাইটর)',
        'specialtyEn': 'General Physician & R.M.O.',
        'experienceBn': '২০+ বছরের চিকিৎসা অভিজ্ঞতা',
        'daysBn': 'প্রতিদিন (রবিবার ব্যতীত)',
        'timingBn': 'সকাল ১০:০০ - দুপুর ১২:০০ এবং সন্ধ্যা ৭:০০ - রাত ৯:০০',
        'visitingFeeBn': '₹ ৫০০',
        'appointmentPhone': '9088377220',
        'appointmentWhatsapp': '+916291123465'
      },
      {
        'id': 'sevatirtham-doc-2',
        'nameBn': 'ডাঃ সুবীর পাল',
        'nameEn': 'Dr. Subir Pal',
        'degrees': 'MBBS, DCH, MD, PGPN (Boston, USA)',
        'specialtyKey': 'pediatrics',
        'specialtyBn': 'শিশু ও নবজাতক রোগ বিশেষজ্ঞ',
        'specialtyEn': 'Child Specialist & Neonatologist',
        'experienceBn': '১৫+ বছরের বিশেষ অভিজ্ঞতা',
        'daysBn': 'প্রতিদিন',
        'timingBn': 'সন্ধ্যা ৭:০০ - রাত ৯:০০',
        'visitingFeeBn': '₹ ৭০০',
        'appointmentPhone': '9088377220',
        'appointmentWhatsapp': '+916291123465'
      },
      {
        'id': 'sevatirtham-doc-3',
        'nameBn': 'ডাঃ শুভাশিস নস্কর',
        'nameEn': 'Dr. Subhasis Naskar',
        'degrees': 'MBBS, MS (General Surgery), DA',
        'specialtyKey': 'general_surgery',
        'specialtyBn': 'জেনারেল ও ল্যাপারোস্কোপিক সার্জন',
        'specialtyEn': 'General & Laparoscopic Surgeon',
        'experienceBn': '১২+ বছরের সার্জিক্যাল অভিজ্ঞতা',
        'daysBn': 'সোমবার ও শুক্রবার',
        'timingBn': 'সোমবার সকাল ১০:৩০, শুক্রবার দুপুর ১:৩০',
        'visitingFeeBn': '₹ ৭০০',
        'appointmentPhone': '9088377220',
        'appointmentWhatsapp': '+916291123465'
      },
      {
        'id': 'sevatirtham-doc-4',
        'nameBn': 'ডাঃ সন্দীপ সরদার',
        'nameEn': 'Dr. Sandip Sardar',
        'degrees': 'MBBS (Cal), MD (Dermatology, Venereology & Leprosy)',
        'specialtyKey': 'dermatology',
        'specialtyBn': 'চর্ম, যৌন ও কুষ্ঠ রোগ বিশেষজ্ঞ',
        'specialtyEn': 'Consultant Dermatologist',
        'experienceBn': '১০+ বছরের অভিজ্ঞতা',
        'daysBn': 'সোমবার ও বৃহস্পতিবার',
        'timingBn': 'সকাল ১১:০০',
        'visitingFeeBn': '₹ ৬০০',
        'appointmentPhone': '9088377220',
        'appointmentWhatsapp': '+916291123465'
      },
      {
        'id': 'sevatirtham-doc-5',
        'nameBn': 'ডাঃ সুবীর দত্ত',
        'nameEn': 'Dr. Subir Dutta',
        'degrees': 'MBBS, General Physician',
        'specialtyKey': 'general_physician',
        'specialtyBn': 'জেনারেল ফিজিশিয়ান (অন কল)',
        'specialtyEn': 'General Physician',
        'experienceBn': '১০+ বছরের অভিজ্ঞতা',
        'daysBn': 'অন কল (জরুরি ও প্রয়োজনমাফিক)',
        'timingBn': 'জরুরি কল মারফত নির্ধারিত',
        'visitingFeeBn': '₹ ৫০০',
        'appointmentPhone': '9088377220',
        'appointmentWhatsapp': '+916291123465'
      }
    ]
  },
  {
    'slug': 'santiniketan-nursing-home-baruipur',
    'nameBn': 'শান্তিনিকেতন নার্সিং হোম অ্যান্ড সোসাইটি',
    'nameEn': 'Santiniketan Nursing Home & Society',
    'type': 'nursing_home',
    'typeBn': 'নার্সিং হোম ও মেটারনিটি কেয়ার',
    'taglineBn': 'বারুইপুর মাদাবত রোডে ৩০ শয্যাবিশিষ্ট রেজিস্টার্ড নার্সিং হোম, সার্জারি ও ২৪ ঘণ্টার জরুরি সেবা',
    'overviewBn': 'শান্তিনিকেতন নার্সিং হোম অ্যান্ড সোসাইটি (Shantiniketan Nursing Society) বারুইপুর মহকুমার একটি সুপরিচিত অনুমোদিত ক্লিনিক্যাল এস্টাব্লিশমেন্ট। এটি বারুইপুর রেলওয়ে ৪ নম্বর প্ল্যাটফর্মের কাছে মাদাবত রোড, মাস্টারপাড়া এলাকায় অবস্থিত। প্রয়াত ডাঃ আতিকুর রহমানের উদ্যোগে প্রতিষ্ঠিত এই নার্সিং হোমে ৩০টি অনুমোদিত শয্যা, সাধারণ ও ল্যাপারোস্কোপিক সার্জারি, প্রসূতি ও স্ত্রীরোগ বিভাগ এবং বহির্বিভাগীয় চিকিৎসা সুবিধা রয়েছে।',
    'addressBn': 'মাদাবত রোড, মাস্টারপাড়া / নতুনপাড়া, বারুইপুর, দক্ষিণ ২৪ পরগনা, কলকাতা - ৭০০১৪৪',
    'addressEn': 'Madarat Road, Masterpara, Near Platform No. 4, Baruipur, South 24 Parganas, Kolkata - 700144',
    'landmarkBn': 'বারুইপুর রেলওয়ে স্টেশন ৪ নম্বর প্ল্যাটফর্ম ও নিকন স্টুডিও সংলগ্ন',
    'phone': '7044410441',
    'altPhone': '7044410442',
    'emergencyPhone': '8282822462',
    'whatsapp': '+917044410441',
    'googleMapUrl': 'https://maps.google.com/?q=Santiniketan+Nursing+Home+Baruipur',
    'openingHoursBn': 'জরুরি বিভাগ ও ইনডোর: ২৪ ঘণ্টা খোলা | বহির্বিভাগ (OPD): সকাল ৯:০০ - রাত ৮:০০',
    'isOpen24Hours': True,
    'hasEmergency': True,
    'hasPharmacy': True,
    'hasDiagnostic': True,
    'hasAmbulance': True,
    'swasthyaSathiAccepted': False,
    'insuranceAccepted': True,
    'establishedYear': '২০১০',
    'bedCapacity': '৩০ শয্যা',
    'keyServicesBn': [
      '২৪ ঘণ্টা ইনপেশেন্ট ভর্তি ও জরুরি পর্যবেক্ষণ',
      'জেনারেল সার্জারি ও ল্যাপারোস্কোপিক অপারেশন',
      'ম্যাটারনিটি ইউনিট, নরমাল ও সিজারিয়ান ডেলিভারি',
      'মেডিক্লেইম ও হেলথ ইনস্যুরেন্স সহায়তা',
      'ইন-হাউস ফার্মেসি ও প্যাথলজি কালেকশন'
    ],
    'diagnosticFacilitiesBn': [
      'ডিজিটাল এক্স-রে',
      'ইউএসজি (USG)',
      'ইসিজি (ECG)',
      'রুটিন প্যাথলজিক্যাল রক্ত ও মূত্র পরীক্ষা'
    ],
    'doctorsCount': 2,
    'doctors': [
      {
        'id': 'santiniketan-doc-1',
        'nameBn': 'ডাঃ রিমা সুলতানা',
        'nameEn': 'Dr. Rima Sultana',
        'degrees': 'MBBS, MS (General Surgery), FMAS, FIAGES',
        'specialtyKey': 'general_surgery',
        'specialtyBn': 'জেনারেল ও ল্যাপারোস্কোপিক সার্জন',
        'specialtyEn': 'Consultant General & Laparoscopic Surgeon',
        'experienceBn': '৮+ বছরের সার্জিক্যাল অভিজ্ঞতা',
        'daysBn': 'কল মারফত নির্ধারিত দিন ও সময়',
        'timingBn': 'পূর্ব বুকিং অনুযায়ী',
        'visitingFeeBn': '₹ ৭০০',
        'appointmentPhone': '7044410441'
      },
      {
        'id': 'santiniketan-doc-2',
        'nameBn': 'ডাঃ নিলোফার আনজুম',
        'nameEn': 'Dr. Nilofar Anjum',
        'degrees': 'MBBS, General Physician',
        'specialtyKey': 'general_physician',
        'specialtyBn': 'জেনারেল ফিজিশিয়ান ও পারিবারিক চিকিৎসক',
        'specialtyEn': 'General Physician',
        'experienceBn': '৭+ বছরের অভিজ্ঞতা',
        'daysBn': 'সোম থেকে শনিবার',
        'timingBn': 'সকাল ১০:০০ - দুপুর ১:০০',
        'visitingFeeBn': '₹ ৫০০',
        'appointmentPhone': '7044410441'
      }
    ]
  },
  {
    'slug': 'well-care-nursing-home-baruipur',
    'nameBn': 'ওয়েল কেয়ার নার্সিং হোম',
    'nameEn': 'Well Care Nursing Home',
    'type': 'nursing_home',
    'typeBn': 'মাল্টি-স্পেশালিটি নার্সিং হোম ও আইসিইউ ডায়ালিসিস সেন্টার',
    'taglineBn': 'বারুইপুরে ডায়ালিসিসযুক্ত সর্বাধুনিক আইসিইউ, ৫০+ শয্যা ও ২৪x৭ জরুরি সুপারস্পেশালিটি কেয়ার',
    'overviewBn': 'ওয়েল কেয়ার নার্সিং হোম (Well Care Nursing Home Baruipur) বারুইপুর-মল্লিকপুর রোডে জুগিবাতলায় অবস্থিত দক্ষিণ ২৪ পরগনার অন্যতম প্রধান ও সর্বাধুনিক পরিকাঠামোযুক্ত প্রাইভেট হাসপাতাল। এখানে রয়েছে বারুইপুর অঞ্চলের প্রথম পূর্ণাঙ্গ ডায়ালিসিস সুবিধাযুক্ত আইসিইউ (ICU with Dialysis), ৫০টিরও বেশি শয্যা, শীতাতপ নিয়ন্ত্রিত কেবিন, আধুনিক অপারেশন থিয়েটার এবং ১৬ জনেরও বেশি প্রখ্যাত বিশেষজ্ঞ ও সুপার-স্পেশালিস্ট চিকিৎসকদের ওপিডি প্যানেল। এখানে ২৪ ঘণ্টা জরুরি পরিষেবা, ক্যাশলেস মেডিক্লেইম এবং সার্বক্ষণিক ফার্মেসি সেবা প্রদান করা হয়।',
    'addressBn': 'জুগিবাতলা, মল্লিকপুর রোড (পি.সি. সরকার বাড়ির নিকট), বারুইপুর, দক্ষিণ ২৪ পরগনা, কলকাতা - ৭০০১৪৫',
    "addressEn": "Dehimedan Malla, Jugibattala, towards Mallickpur Road, near P.C. Sorcar's House, Baruipur, South 24 Parganas, Kolkata - 700145",
    'landmarkBn': 'জুগিবাতলা, মল্লিকপুর রোড, পি.সি. সরকারের বাড়ির সন্নিকটে',
    'phone': '9475332013',
    'altPhone': '9475332013',
    'emergencyPhone': '9475332013',
    'whatsapp': '+919475332013',
    'email': 'wellcarenursinghome0@gmail.com',
    'website': 'https://www.wellcarenursinghome.com',
    'googleMapUrl': 'https://maps.google.com/?q=Well+Care+Nursing+Home+Baruipur',
    'openingHoursBn': 'জরুরি বিভাগ, আইসিইউ ও ইনডোর: ২৪ ঘণ্টা খোলা | ওপিডি: সকাল ৮:০০ - রাত ৮:০০',
    'isOpen24Hours': True,
    'hasEmergency': True,
    'hasPharmacy': True,
    'hasDiagnostic': True,
    'hasAmbulance': True,
    'swasthyaSathiAccepted': False,
    'insuranceAccepted': True,
    'establishedYear': '২০২২',
    'bedCapacity': '৫০+ শয্যা',
    'keyServicesBn': [
      'ডায়ালিসিস সুবিধাযুক্ত অত্যাধুনিক ক্রিটিক্যাল কেয়ার আইসিইউ (ICU with Dialysis)',
      '৫০+ শয্যাবিশিষ্ট সুসজ্জিত সাধারণ ওয়ার্ড ও ডিলাক্স এসি কেবিন',
      'মডুলার অপারেশন থিয়েটার ও ল্যাপারোস্কোপিক, অর্থোপেডিক এবং অনকো-সার্জারি',
      '২৪ ঘণ্টা জরুরি ট্রমা কেয়ার, অ্যাম্বুলেন্স ও সার্বক্ষণিক ফার্মেসি',
      'ক্যাশলেস মেডিক্লেইম ও সমস্ত প্রধান ইনস্যুরেন্স টিপিএ (TPA) সুবিধা',
      'সুপারস্পেশালিটি ওপিডি কনসাল্টেশন (কার্ডিওলজি, নিউরো, গ্যাস্ট্রো, অনকোলজি, নেফ্রোলজি)'
    ],
    'diagnosticFacilitiesBn': [
      'ডিজিটাল এক্স-রে (Digital X-Ray)',
      'কালার ডপলার ও আল্ট্রাসনোগ্রাফি (USG)',
      '১২-লিড ইসিজি ও কার্ডিয়াক মনিটরিং',
      'সম্পূর্ণ স্বয়ংক্রিয় বায়োকেমিস্ট্রি, হেমাটোলজি ও হরমোন প্যাথলজি ল্যাব'
    ],
    'doctorsCount': 16,
    'doctors': [
      {
        'id': 'wellcare-doc-1',
        'nameBn': 'ডাঃ বিক্রম মণ্ডল',
        'nameEn': 'Dr. Bikram Mondal',
        'degrees': 'MBBS, MD (Pediatrics)',
        'specialtyKey': 'pediatrics',
        'specialtyBn': 'শিশু ও নবজাতক রোগ বিশেষজ্ঞ',
        'specialtyEn': 'Pediatrician & Neonatologist',
        'experienceBn': '১০+ বছরের চিকিৎসা অভিজ্ঞতা',
        'daysBn': 'সোম, বুধ ও শুক্রবার',
        'timingBn': 'সন্ধ্যা ৬:০০ - রাত ৮:০০',
        'visitingFeeBn': '₹ ৭০০',
        'appointmentPhone': '9475332013'
      },
      {
        'id': 'wellcare-doc-2',
        'nameBn': 'ডাঃ চিরন্তন মণ্ডল',
        'nameEn': 'Dr. Chirantan Mondal',
        'degrees': 'MBBS, MS (OBS & Gynae), Ex-Senior House Surgeon NRS Medical College & National Hospital',
        'specialtyKey': 'gynecology',
        'specialtyBn': 'স্ত্রীরোগ ও প্রসূতি বিশেষজ্ঞ সার্জন',
        'specialtyEn': 'Gynaecologist & Obstetrician',
        'experienceBn': '১২+ বছরের বিশেষ অভিজ্ঞতা',
        'daysBn': 'সোম ও বৃহস্পতিবার',
        'timingBn': 'বিকাল ৫:০০ - সন্ধ্যা ৭:০০',
        'visitingFeeBn': '₹ ৭০০',
        'appointmentPhone': '9475332013'
      },
      {
        'id': 'wellcare-doc-3',
        'nameBn': 'ডাঃ দেবাশিস নস্কর',
        'nameEn': 'Dr. Debasis Naskar',
        'degrees': 'MBBS, MS (Ortho), AO (Trauma Adv.), Observership NUH Singapore, Associate Professor JIMSH',
        'specialtyKey': 'orthopedics',
        'specialtyBn': 'অর্থোপেডিক ও ট্রমা বিশেষজ্ঞ সার্জন',
        'specialtyEn': 'Consultant Orthopaedic Surgeon',
        'experienceBn': '১৫+ বছরের অর্থোপেডিক অভিজ্ঞতা',
        'daysBn': 'মঙ্গলবার ও শনিবার',
        'timingBn': 'সন্ধ্যা ৬:০০ - রাত ৮:৩০',
        'visitingFeeBn': '₹ ৮০০',
        'appointmentPhone': '9475332013'
      },
      {
        'id': 'wellcare-doc-4',
        'nameBn': 'ডাঃ কোয়েল হালদার',
        'nameEn': 'Dr. Koyel Halder',
        'degrees': 'MBBS (Cal), MS (OBS & Gynae, Kol), WBMC Reg. 67408',
        'specialtyKey': 'gynecology',
        'specialtyBn': 'স্ত্রীরোগ ও প্রসূতি বিশেষজ্ঞ',
        'specialtyEn': 'Consultant Gynaecologist',
        'experienceBn': '৯+ বছরের অভিজ্ঞতা',
        'daysBn': 'বুধবার ও রবিবার',
        'timingBn': 'সকাল ১১:০০ - দুপুর ১:০০',
        'visitingFeeBn': '₹ ৭০০',
        'appointmentPhone': '9475332013'
      },
      {
        'id': 'wellcare-doc-5',
        'nameBn': 'ডাঃ কুণাল মণ্ডল',
        'nameEn': 'Dr. Kunal Mondal',
        'degrees': 'MBBS (CNMC), MS (Orthopedics, IPGMER & SSKM), DNB (Ortho), Fellowship in Arthroscopy (WBOA)',
        'specialtyKey': 'orthopedics',
        'specialtyBn': 'অর্থোপেডিক, জয়েন্ট রিপ্লেসমেন্ট ও আর্থ্রোস্কোপি সার্জন',
        'specialtyEn': 'Orthopaedic & Arthroscopy Surgeon',
        'experienceBn': '১০+ বছরের বিশেষজ্ঞ অভিজ্ঞতা',
        'daysBn': 'বুধবার ও শুক্রবার',
        'timingBn': 'সন্ধ্যা ৬:৩০ - রাত ৮:৩০',
        'visitingFeeBn': '₹ ৮০০',
        'appointmentPhone': '9475332013'
      },
      {
        'id': 'wellcare-doc-6',
        'nameBn': 'ডাঃ মেহেরাজ সেখ',
        'nameEn': 'Dr. Meheraj Sk',
        'degrees': 'MBBS, MS (General Surgery), MCh (Plastic & Reconstructive Surgery), DrNB (Urology)',
        'specialtyKey': 'urology',
        'specialtyBn': 'ইউরোলজি, জেনারেল ও প্লাস্টিক সার্জারি বিশেষজ্ঞ',
        'specialtyEn': 'Consultant Urologist & Plastic Surgeon',
        'experienceBn': '১১+ বছরের অভিজ্ঞতা',
        'daysBn': 'বৃহস্পতিবার',
        'timingBn': 'বিকাল ৪:০০ - সন্ধ্যা ৬:০০',
        'visitingFeeBn': '₹ ৯০০',
        'appointmentPhone': '9475332013'
      },
      {
        'id': 'wellcare-doc-7',
        'nameBn': 'ডাঃ শুভাশিস নস্কর',
        'nameEn': 'Dr. Subhasis Naskar',
        'degrees': 'MBBS, MS (General Surgery), DA',
        'specialtyKey': 'general_surgery',
        'specialtyBn': 'জেনারেল ও ল্যাপারোস্কোপিক সার্জন',
        'specialtyEn': 'Consultant General Surgeon',
        'experienceBn': '১২+ বছরের সার্জিক্যাল অভিজ্ঞতা',
        'daysBn': 'মঙ্গলবার ও শুক্রবার',
        'timingBn': 'দুপুর ১২:০০ - দুপুর ২:০০',
        'visitingFeeBn': '₹ ৭০০',
        'appointmentPhone': '9475332013'
      },
      {
        'id': 'wellcare-doc-8',
        'nameBn': 'ডাঃ সুবীর পাল',
        'nameEn': 'Dr. Subir Pal',
        'degrees': 'MBBS, DCH, MD, PGPN (Boston, USA)',
        'specialtyKey': 'pediatrics',
        'specialtyBn': 'শিশু ও নবজাতক বিশেষজ্ঞ',
        'specialtyEn': 'Child Specialist & Neonatologist',
        'experienceBn': '১৫+ বছরের অভিজ্ঞতা',
        'daysBn': 'সোম থেকে শনিবার',
        'timingBn': 'সন্ধ্যা ৫:০০ - সন্ধ্যা ৭:০০',
        'visitingFeeBn': '₹ ৭০০',
        'appointmentPhone': '9475332013'
      },
      {
        'id': 'wellcare-doc-9',
        'nameBn': 'ডাঃ রাহুল নস্কর',
        'nameEn': 'Dr. Rahul Naskar',
        'degrees': 'MBBS, MS (General Surgery), MRCS (Eng.)',
        'specialtyKey': 'general_surgery',
        'specialtyBn': 'ল্যাপারোস্কোপিক, জিআই ও জেনারেল সার্জন',
        'specialtyEn': 'Consultant Laparoscopic & GI Surgeon',
        'experienceBn': '৮+ বছরের সার্জিক্যাল অভিজ্ঞতা',
        'daysBn': 'সোমবার ও বুধবার',
        'timingBn': 'সন্ধ্যা ৬:০০ - রাত ৮:০০',
        'visitingFeeBn': '₹ ৮০০',
        'appointmentPhone': '9475332013'
      },
      {
        'id': 'wellcare-doc-10',
        'nameBn': 'ডাঃ রাহুল ভঞ্জ চৌধুরী',
        'nameEn': 'Dr. Rahul Bhanj Chowdhury',
        'degrees': 'MBBS, MS (General Surgery), MRCS (Edinburgh), FMAS (AMASI)',
        'specialtyKey': 'general_surgery',
        'specialtyBn': 'জেনারেল, ল্যাপারোস্কোপিক ও জিআই সার্জন',
        'specialtyEn': 'Consultant Laparoscopic Surgeon',
        'experienceBn': '১০+ বছরের অভিজ্ঞতা',
        'daysBn': 'মঙ্গলবার',
        'timingBn': 'বিকাল ৫:০০ - সন্ধ্যা ৭:০০',
        'visitingFeeBn': '₹ ৮০০',
        'appointmentPhone': '9475332013'
      },
      {
        'id': 'wellcare-doc-11',
        'nameBn': 'ডাঃ রাহুল ধর',
        'nameEn': 'Dr. Rahul Dhar',
        'degrees': 'MBBS (WBUHS), MS (General Surgery, IPGMER), MRCS (Edinburgh)',
        'specialtyKey': 'gastroenterology',
        'specialtyBn': 'সার্জিক্যাল গ্যাস্ট্রোএন্টারোলজি বিশেষজ্ঞ',
        'specialtyEn': 'Consultant Surgical Gastroenterologist',
        'experienceBn': '৯+ বছরের অভিজ্ঞতা',
        'daysBn': 'বৃহস্পতিবার ও শনিবার',
        'timingBn': 'সন্ধ্যা ৬:০০ - রাত ৮:০০',
        'visitingFeeBn': '₹ ৯০০',
        'appointmentPhone': '9475332013'
      },
      {
        'id': 'wellcare-doc-12',
        'nameBn': 'ডাঃ ইন্দ্রজিৎ মল্লিক',
        'nameEn': 'Dr. Indrajit Malik',
        'degrees': 'MBBS (Cal), MS (General Surgery, NRSMCH), DrNB (Surgical Oncology)',
        'specialtyKey': 'oncology',
        'specialtyBn': 'ক্যান্সার সার্জারি বিশেষজ্ঞ (সার্জিক্যাল অনকোলজিস্ট)',
        'specialtyEn': 'Consultant Surgical Oncologist',
        'experienceBn': '১১+ বছরের অভিজ্ঞতা',
        'daysBn': 'শুক্রবার',
        'timingBn': 'সন্ধ্যা ৬:০০ - রাত ৮:০০',
        'visitingFeeBn': '₹ ১,০০০',
        'appointmentPhone': '9475332013'
      },
      {
        'id': 'wellcare-doc-13',
        'nameBn': 'ডাঃ অরিজিৎ বিষ্ণু',
        'nameEn': 'Dr. Arijit Bishnu',
        'degrees': 'MBBS, MD, DM (Clinical Hematology)',
        'specialtyKey': 'hematology',
        'specialtyBn': 'হেমাটোলজি, ব্লাড ক্যান্সার ও বিএমটি বিশেষজ্ঞ',
        'specialtyEn': 'Consultant Haematology-Oncologist & BMT Physician',
        'experienceBn': '১০+ বছরের অভিজ্ঞতা',
        'daysBn': 'শনিবার',
        'timingBn': 'বিকাল ৪:০০ - সন্ধ্যা ৬:০০',
        'visitingFeeBn': '₹ ১,০০০',
        'appointmentPhone': '9475332013'
      },
      {
        'id': 'wellcare-doc-14',
        'nameBn': 'ডাঃ রাজন কুমার',
        'nameEn': 'Dr. Rajan Kumar',
        'degrees': 'MBBS, MS (General Surgery), MCh (Neurosurgery)',
        'specialtyKey': 'neurology',
        'specialtyBn': 'নিউরোসার্জন (মস্তিষ্ক ও স্পাইন সার্জারি বিশেষজ্ঞ)',
        'specialtyEn': 'Consultant Neurosurgeon',
        'experienceBn': '১০+ বছরের অভিজ্ঞতা',
        'daysBn': 'বুধবার',
        'timingBn': 'বিকাল ৫:০০ - সন্ধ্যা ৭:০০',
        'visitingFeeBn': '₹ ১,০০০',
        'appointmentPhone': '9475332013'
      },
      {
        'id': 'wellcare-doc-15',
        'nameBn': 'ডাঃ সাব্বির আহমেদ',
        'nameEn': 'Dr. Sabbir Ahamed',
        'degrees': 'MBBS (Kol), DNB (Internal Medicine), DFM (WBUHS), CCEBDM, Eular Fellow in Rheumatology (UK), Ex-SR AIIMS',
        'specialtyKey': 'general_medicine',
        'specialtyBn': 'মেডিসিন, ডায়াবেটিস ও বাত রোগ বিশেষজ্ঞ (রিউমাটোলজিস্ট)',
        'specialtyEn': 'Consultant Physician & Rheumatologist',
        'experienceBn': '১২+ বছরের অভিজ্ঞতা',
        'daysBn': 'সোম, বুধ ও শুক্রবার',
        'timingBn': 'সন্ধ্যা ৬:০০ - রাত ৮:৩০',
        'visitingFeeBn': '₹ ৮০০',
        'appointmentPhone': '9475332013'
      },
      {
        'id': 'wellcare-doc-16',
        'nameBn': 'ডাঃ সৌম্য ভট্টাচার্য',
        'nameEn': 'Dr. Soumya Bhattacharya',
        'degrees': 'MBBS, MD, CCEBDM, Ex-Senior Resident AIIMS Delhi & R.N. Tagore Hospital',
        'specialtyKey': 'general_medicine',
        'specialtyBn': 'জেনারেল মেডিসিন, ক্রিটিক্যাল কেয়ার ও ডায়াবেটিস বিশেষজ্ঞ',
        'specialtyEn': 'Consultant Physician & Intensivist',
        'experienceBn': '১১+ বছরের অভিজ্ঞতা',
        'daysBn': 'মঙ্গল, বৃহস্পতি ও শনিবার',
        'timingBn': 'সন্ধ্যা ৬:০০ - রাত ৮:৩০',
        'visitingFeeBn': '₹ ৭০০',
        'appointmentPhone': '9475332013'
      }
    ]
  }
]

with open('src/data/healthcare_data.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

existing_slugs = {x['slug']: i for i, x in enumerate(data)}
added = 0
for fac in new_facilities:
    if fac['slug'] in existing_slugs:
        data[existing_slugs[fac['slug']]] = fac
        print('Updated:', fac['slug'])
    else:
        data.append(fac)
        added += 1
        print('Added:', fac['slug'])

with open('src/data/healthcare_data.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print('Success! Total facilities now:', len(data))
